#!/usr/bin/env node

/**
 * Public API surface gate.
 *
 * `check:exports` proves the published types *resolve*. Nothing proved the
 * published *shape* had not moved. A refactor could widen a parameter, drop an
 * overload, or rename an exported type, and lint, typecheck, tests, attw,
 * publint, size and smoke would all still pass: none of them knows what the
 * surface looked like yesterday.
 *
 * This script extracts the surface from the generated declarations and compares
 * it against the committed `api-surface.txt`. On a mismatch it prints a unified
 * diff and exits non-zero. `--update` rewrites the snapshot, which is how an
 * intentional API change is approved -- in the same commit that makes it, so
 * the diff is reviewed alongside the change rather than discovered after
 * release.
 *
 * Reads the ESM declarations only. `dist/*.d.cts` is emitted from the same
 * sources by the same tsup run, and `check:exports` covers its resolution.
 *
 * The snapshot is one line per declaration, or per member of one:
 *
 *     <module> <path>  <normalised declaration text>
 *
 * so a changed parameter list is a one-line diff rather than a rewritten file,
 * and a new export inserts a single line. There is no column alignment for the
 * same reason: padding would rewrite every line the first time a longer name
 * appears. Comments are dropped and whitespace collapsed, so reformatting the
 * sources does not churn the snapshot, while every parameter, modifier and
 * return type is kept verbatim.
 *
 * A `~` prefix marks a declaration that is not itself exported but is reachable
 * from one that is -- `type UnitAlias = keyof typeof UNIT_ALIASES` puts the
 * shape of `UNIT_ALIASES` in the contract whether or not it is importable, so a
 * new unit alias has to show up here too. The `type` modifier of an export
 * clause is not recorded: the declaration text already says whether an entry is
 * a value or a type.
 *
 * Zero dependencies, and deliberately no TypeScript compiler API: the input is
 * generated by one pinned emitter, always in the same shape, and a scanner over
 * it is a fraction of the cost of loading and configuring a program.
 *
 * Usage:
 *   node scripts/api-surface.mjs            # verify against the snapshot
 *   node scripts/api-surface.mjs --update   # rewrite the snapshot
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const snapshotPath = join(root, 'api-surface.txt');

/** Every entry point the package advertises, and the module name consumers use. */
const ENTRY_POINTS = [
  { module: 'timesolver', file: 'index.d.ts' },
  { module: 'timesolver/profiler', file: 'profiler.d.ts' },
];

/** Maps the specifiers the declarations import from onto those module names. */
const MODULE_BY_SPECIFIER = new Map([
  ['./index.js', 'timesolver'],
  ['./profiler.js', 'timesolver/profiler'],
]);

/** Written into the snapshot, so the file explains itself to whoever opens it. */
const HEADER = [
  '# timesolver public API surface, extracted from dist/ by scripts/api-surface.mjs.',
  '# One line per exported declaration or member:  <module> <path>  <declaration>',
  '# A ~ prefix marks a declaration reachable from the surface but not exported.',
  '#',
  '# Generated; do not edit by hand. After an intentional API change, run:',
  '#   npm run build && npm run check:api -- --update',
];

/** Statements whose closing brace ends them, with no terminating semicolon. */
const BLOCK_BODY =
  /^(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(?:class|interface|namespace|module|enum|global)\b/;
const IMPORT_CLAUSE = /^import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+(['"])([^'"]+)\2$/;
const EXPORT_CLAUSE = /^export\s+(?:type\s+)?\{([^}]*)\}(?:\s+from\s+(['"])([^'"]+)\2)?$/;
const EXPORT_STAR = /^export\s+\*/;
const EXPORT_DEFAULT = /^export\s+default\s+([A-Za-z_$][\w$]*)$/;
const SPECIFIER = /^(?:type\s+)?([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*|default))?$/;
const DECLARATION =
  /^(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(?:function|const|let|var|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/;
const MEMBER_NAME =
  /^(?:(?:readonly|static|public|private|protected|abstract|declare|get|set|async)\s+)*(\[[^\]]*\]|'[^']*'|"[^"]*"|[A-Za-z_$][\w$]*)/;
const IDENTIFIER = /[A-Za-z_$][\w$]*/g;

function fail(summary, detail) {
  console.error(`api-surface failed - ${summary}`);
  if (detail) {
    console.error('');
    console.error(detail);
  }
  process.exit(1);
}

/** End index, exclusive, of the string or template literal starting at `start`. */
function endOfLiteral(source, start) {
  const quote = source[start];
  let i = start + 1;
  while (i < source.length) {
    if (source[i] === '\\') {
      i += 2;
      continue;
    }
    if (source[i] === quote) return i + 1;
    i += 1;
  }
  return source.length;
}

/**
 * Replace every comment with a single space, so doc comments cannot leak into
 * the surface and cannot glue two tokens together either.
 */
function stripComments(source) {
  let out = '';
  let i = 0;
  while (i < source.length) {
    const ch = source[i];
    const next = source[i + 1];
    if (ch === '/' && next === '*') {
      const end = source.indexOf('*/', i + 2);
      i = end === -1 ? source.length : end + 2;
      out += ' ';
    } else if (ch === '/' && next === '/') {
      const end = source.indexOf('\n', i + 2);
      i = end === -1 ? source.length : end;
      out += ' ';
    } else if (ch === '"' || ch === "'" || ch === '`') {
      const end = endOfLiteral(source, i);
      out += source.slice(i, end);
      i = end;
    } else {
      out += ch;
      i += 1;
    }
  }
  return out;
}

/** Split a declaration file into top-level statements. */
function splitStatements(source) {
  const out = [];
  let start = 0;
  let depth = 0;
  let i = 0;
  while (i < source.length) {
    const ch = source[i];
    if (ch === '"' || ch === "'" || ch === '`') {
      i = endOfLiteral(source, i);
      continue;
    }
    if (ch === '{' || ch === '(' || ch === '[') depth += 1;
    else if (ch === '}' || ch === ')' || ch === ']') depth -= 1;
    i += 1;
    if (depth !== 0) continue;
    const statement = source.slice(start, i);
    if (ch === ';' || (ch === '}' && BLOCK_BODY.test(statement.trim()))) {
      out.push(statement);
      start = i;
    }
  }
  out.push(source.slice(start));
  return out
    .map((statement) => statement.replace(/\s+/g, ' ').trim().replace(/;$/, ''))
    .filter(Boolean);
}

/** Strip the noise a declaration file adds around every declaration. */
function declarationText(statement) {
  return statement.replace(/^export\s+/, '').replace(/^declare\s+/, '');
}

/** Index of the `}` matching the `{` at `open`, or -1. */
function matchingBrace(text, open) {
  let depth = 0;
  let i = open;
  while (i < text.length) {
    const ch = text[i];
    if (ch === '"' || ch === "'" || ch === '`') {
      i = endOfLiteral(text, i);
      continue;
    }
    if (ch === '{') depth += 1;
    else if (ch === '}') {
      depth -= 1;
      if (depth === 0) return i;
    }
    i += 1;
  }
  return -1;
}

/** Split a braced body on its top-level semicolons. */
function splitMembers(body) {
  const out = [];
  let depth = 0;
  let start = 0;
  let i = 0;
  while (i < body.length) {
    const ch = body[i];
    if (ch === '"' || ch === "'" || ch === '`') {
      i = endOfLiteral(body, i);
      continue;
    }
    if (ch === '{' || ch === '(' || ch === '[') depth += 1;
    else if (ch === '}' || ch === ')' || ch === ']') depth -= 1;
    i += 1;
    if (depth === 0 && ch === ';') {
      out.push(body.slice(start, i - 1).trim());
      start = i;
    }
  }
  out.push(body.slice(start).trim());
  return out.filter(Boolean);
}

/**
 * Split a declaration into a head and its members, so that adding one member
 * to a thirty-member object is a one-line diff. Anything whose shape is not
 * unambiguously "head followed by one braced body" is left whole.
 */
function splitBody(text) {
  const open = text.indexOf('{');
  if (open === -1 || !text.endsWith('}')) return null;
  if (matchingBrace(text, open) !== text.length - 1) return null;
  const members = splitMembers(text.slice(open + 1, -1).trim());
  if (members.length === 0) return null;
  return { head: `${text.slice(0, open).trim()} { ... }`, members };
}

/** The name a member is addressed by, for the dotted path. */
function memberName(member) {
  const matched = MEMBER_NAME.exec(member);
  return matched ? matched[1] : member;
}

/** Parse one declaration file into declarations, imports and export specifiers. */
function parseModule(module, source) {
  const declarations = new Map();
  const imports = new Map();
  const exported = [];

  for (const statement of splitStatements(stripComments(source))) {
    const importClause = IMPORT_CLAUSE.exec(statement);
    if (importClause) {
      for (const raw of importClause[1].split(',')) {
        const specifier = SPECIFIER.exec(raw.trim());
        if (specifier) {
          imports.set(specifier[2] ?? specifier[1], {
            specifier: importClause[3],
            name: specifier[1],
          });
        }
      }
      continue;
    }
    if (statement.startsWith('import ')) continue;

    const exportClause = EXPORT_CLAUSE.exec(statement);
    if (exportClause) {
      for (const raw of exportClause[1].split(',')) {
        const specifier = SPECIFIER.exec(raw.trim());
        if (specifier) {
          exported.push({
            name: specifier[2] ?? specifier[1],
            local: specifier[1],
            specifier: exportClause[3],
          });
        }
      }
      continue;
    }

    const exportDefault = EXPORT_DEFAULT.exec(statement);
    if (exportDefault) {
      exported.push({ name: 'default', local: exportDefault[1], specifier: undefined });
      continue;
    }

    if (EXPORT_STAR.test(statement)) {
      fail(
        `${module} uses a wildcard re-export`,
        `scripts/api-surface.mjs cannot expand \`${statement}\`, so it would silently\n` +
          'under-report the surface. Teach it to follow wildcard re-exports before\n' +
          'landing one.',
      );
    }

    const declaration = DECLARATION.exec(statement);
    if (declaration) {
      const name = declaration[1];
      const group = declarations.get(name) ?? [];
      group.push(declarationText(statement));
      declarations.set(name, group);
    }
  }

  return { module, declarations, imports, exported };
}

/** Resolve a name in `owner` to the module that declares it and its local name. */
function resolveBinding(owner, local, modules) {
  if (owner.declarations.has(local)) return { owner, local };
  const imported = owner.imports.get(local);
  if (!imported) return null;
  const target = modules.get(MODULE_BY_SPECIFIER.get(imported.specifier));
  if (!target?.declarations.has(imported.name)) return null;
  return { owner: target, local: imported.name };
}

/**
 * Every line of one module's surface: its exports, then the declarations those
 * exports reach into. Members are listed under their parent's dotted path.
 */
function surfaceOf(mod, modules) {
  const lines = [];
  const queue = [];
  /** Declarations already on this surface, under any path. */
  const included = new Set();
  /** Declaration-and-path pairs already queued, so an alias is not lost. */
  const queued = new Set();

  const enqueue = (binding, path) => {
    const declaration = `${binding.owner.module}\u0000${binding.local}`;
    if (queued.has(`${declaration}\u0000${path}`)) return;
    queued.add(`${declaration}\u0000${path}`);
    included.add(declaration);
    queue.push({ ...binding, path });
  };

  // Every export is queued before the loop runs, so a declaration that is
  // exported never also appears as a `~` internal.
  for (const spec of mod.exported) {
    const from = spec.specifier ? modules.get(MODULE_BY_SPECIFIER.get(spec.specifier)) : mod;
    const binding = from ? resolveBinding(from, spec.local, modules) : null;
    if (binding) {
      enqueue(binding, spec.name);
    } else {
      const origin = spec.specifier ? `'${spec.specifier}'` : 'an unresolved binding';
      lines.push({ module: mod.module, path: spec.name, text: `re-exported from ${origin}` });
    }
  }

  while (queue.length > 0) {
    const { owner, local, path } = queue.shift();
    for (const text of owner.declarations.get(local)) {
      const body = splitBody(text);
      lines.push({ module: mod.module, path, text: body ? body.head : text });
      for (const member of body?.members ?? []) {
        lines.push({ module: mod.module, path: `${path}.${memberName(member)}`, text: member });
      }

      // Anything the declaration names is part of the contract too, even when
      // it is not exported: widening it widens the exported type.
      for (const identifier of text.match(IDENTIFIER) ?? []) {
        const reached = resolveBinding(owner, identifier, modules);
        if (!reached) continue;
        if (included.has(`${reached.owner.module}\u0000${reached.local}`)) continue;
        enqueue(reached, `~${identifier}`);
      }
    }
  }

  return lines;
}

/** Codepoint order, never the host locale's collation. */
function compare(a, b) {
  if (a === b) return 0;
  return a < b ? -1 : 1;
}

function renderSurface(lines) {
  const sorted = [...lines].sort(
    (a, b) => compare(a.module, b.module) || compare(a.path, b.path) || compare(a.text, b.text),
  );
  const rendered = sorted.map(({ module, path, text }) => `${module} ${path}  ${text}`);
  return { text: `${[...HEADER, ...rendered].join('\n')}\n`, count: rendered.length };
}

/** Longest-common-subsequence edit script over two arrays of lines. */
function editScript(from, to) {
  const width = to.length + 1;
  const lcs = new Int32Array((from.length + 1) * width);
  for (let i = from.length - 1; i >= 0; i -= 1) {
    for (let j = to.length - 1; j >= 0; j -= 1) {
      lcs[i * width + j] =
        from[i] === to[j]
          ? lcs[(i + 1) * width + j + 1] + 1
          : Math.max(lcs[(i + 1) * width + j], lcs[i * width + j + 1]);
    }
  }

  const script = [];
  let i = 0;
  let j = 0;
  while (i < from.length && j < to.length) {
    if (from[i] === to[j]) {
      script.push({ op: ' ', text: from[i], from: i + 1, to: j + 1 });
      i += 1;
      j += 1;
    } else if (lcs[(i + 1) * width + j] >= lcs[i * width + j + 1]) {
      script.push({ op: '-', text: from[i], from: i + 1, to: j + 1 });
      i += 1;
    } else {
      script.push({ op: '+', text: to[j], from: i + 1, to: j + 1 });
      j += 1;
    }
  }
  while (i < from.length) {
    script.push({ op: '-', text: from[i], from: i + 1, to: j + 1 });
    i += 1;
  }
  while (j < to.length) {
    script.push({ op: '+', text: to[j], from: i + 1, to: j + 1 });
    j += 1;
  }
  return script;
}

/** A unified diff, or '' when the two sides are identical. */
function unifiedDiff(from, to, fromLabel, toLabel, context = 3) {
  const script = editScript(from, to);
  const changed = script.flatMap((row, index) => (row.op === ' ' ? [] : [index]));
  if (changed.length === 0) return '';

  const groups = [];
  for (const index of changed) {
    const last = groups.at(-1);
    if (last && index - last.end <= context * 2) last.end = index;
    else groups.push({ start: index, end: index });
  }

  const out = [`--- ${fromLabel}`, `+++ ${toLabel}`];
  for (const group of groups) {
    const rows = script.slice(
      Math.max(0, group.start - context),
      Math.min(script.length, group.end + context + 1),
    );
    const fromCount = rows.filter((row) => row.op !== '+').length;
    const toCount = rows.filter((row) => row.op !== '-').length;
    const fromStart = rows.find((row) => row.op !== '+')?.from ?? rows[0].from;
    const toStart = rows.find((row) => row.op !== '-')?.to ?? rows[0].to;
    out.push(`@@ -${fromStart},${fromCount} +${toStart},${toCount} @@`);
    for (const row of rows) out.push(`${row.op}${row.text}`);
  }
  return out.join('\n');
}

function toLines(text) {
  return text.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n');
}

const args = process.argv.slice(2);
const update = args.includes('--update') || args.includes('-u');
const unknown = args.filter((arg) => arg !== '--update' && arg !== '-u');
if (unknown.length > 0) {
  console.error(`api-surface: unrecognised argument ${unknown[0]}`);
  console.error('');
  console.error('Usage: node scripts/api-surface.mjs [--update]');
  process.exit(2);
}

if (!existsSync(dist)) {
  fail(
    'dist/ is missing',
    'The surface is read from the generated declarations, so there is nothing to\n' +
      'compare yet. Run `npm run build`, then run this check again.',
  );
}

const modules = new Map();
for (const entry of ENTRY_POINTS) {
  const file = join(dist, entry.file);
  if (!existsSync(file)) {
    fail(
      `dist/${entry.file} is missing`,
      `The build did not emit declarations for '${entry.module}'.\n` +
        'Run `npm run build`, then run this check again.',
    );
  }
  modules.set(entry.module, parseModule(entry.module, readFileSync(file, 'utf8')));
}

const surface = [];
for (const mod of modules.values()) surface.push(...surfaceOf(mod, modules));
const generated = renderSurface(surface);
const committed = existsSync(snapshotPath) ? readFileSync(snapshotPath, 'utf8') : null;
const diff =
  committed === null
    ? ''
    : unifiedDiff(
        toLines(committed),
        toLines(generated.text),
        'api-surface.txt',
        'dist/ (generated)',
      );

if (update) {
  writeFileSync(snapshotPath, generated.text);
  if (committed === null) {
    console.log(`api-surface updated - wrote api-surface.txt with ${generated.count} entries.`);
  } else if (diff === '') {
    console.log(`api-surface updated - no change; ${generated.count} entries already recorded.`);
  } else {
    console.log(diff);
    console.log('');
    console.log(
      `api-surface updated - api-surface.txt now records ${generated.count} entries. ` +
        'Commit it with the change that moved the surface.',
    );
  }
  process.exit(0);
}

if (committed === null) {
  fail(
    'api-surface.txt is missing',
    'There is no approved surface to compare against.\n' +
      'Run `npm run check:api -- --update` and commit the generated file.',
  );
}

if (diff === '') {
  console.log(
    `api-surface passed - ${generated.count} entries match api-surface.txt across ` +
      `${ENTRY_POINTS.map((entry) => entry.module).join(' and ')}.`,
  );
  process.exit(0);
}

console.error(diff);
fail(
  'the public API surface does not match api-surface.txt',
  'Lines marked - are in the approved snapshot but not in the build; lines marked\n' +
    '+ are in the build but not approved.\n' +
    '\n' +
    'If this change is intentional, run `npm run check:api -- --update` and commit\n' +
    'api-surface.txt alongside it, so the surface change is reviewed with the code\n' +
    'that caused it. If it is not, the build changed the published API by accident.',
);
